# Site settings
title: 江湖-郎中-路
header-img: img/home-bg.jpg
email: 29392964@qq.com
copyright_name: nndou
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://blog.nndou.com"
github_username:  29392964
email_username:  29392964@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
